# Generated by Django 5.1.4 on 2024-12-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Заблокированная статья'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликованная'),
        ),
        migrations.DeleteModel(
            name='TagArticle',
        ),
    ]
