# Generated by Django 5.1.4 on 2024-12-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_article_tags_article_is_banned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='card_description',
        ),
    ]
