# Generated by Django 5.1.4 on 2024-12-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_article_card_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создание статьи'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения статьи'),
        ),
        migrations.DeleteModel(
            name='FavoriteArticle',
        ),
    ]
